### PR TITLE
fix: boolean group field on actions

### LINKED ISSUE #2569: Boolean Group Field in action fields yields to unpermitted param
### Describe the bug
See title

### Steps to Reproduce
1. Create an action for resource
2. Add boolean_group field in action
3. Submit
4. boolean_group field is unpermitted and unavailable in handle method fields parameter

### System configuration
**Avo version**: 3.4.4

**Rails version**: 7.1.3.2

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x ] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [ ] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #2569

Boolean group field was not respecting the form scope. For this reason, on actions, it's values was getting passed through params outside `fields` scope behaving as unpermitted params.

This PR also drops `record` dependency for boolean group fields. Now it can be used for example on an action from index view.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by gabrielgiroe1 — APPROVED** [review]

File: app/components/avo/fields/boolean_group_field/edit_component.rb [hunk 1]
```diff
@@ -1,4 +1,23 @@
 # frozen_string_literal: true
 
 class Avo::Fields::BooleanGroupField::EditComponent < Avo::Fields::EditComponent
+  def initialize(...)
+    super(...)
+
+    # Initilize here to avoid multiple calls to @field.get_html for each option.
```
Comment (adrianthedev) [inline app/components/avo/fields/boolean_group_field/edit_component.rb:7]: ❤️

**Review by adrianthedev — APPROVED** [review]
Looks great! Thanks!
