### PR TITLE
fix: radio field on actions & improve accessibility

### LINKED ISSUE #3539: radio within action fields gets wrong labels
### Describe the bug
If I use this code
```ruby
          field :subscription_state,
                as: :radio,
                name: 'Status',
                options: {
                  proposal: 'Uitnodigen',
                  confirmed: 'Bevestigen',
                  reserve: 'Reserve'
                }
```

within a resource it works fine
Image

but within an action it doesn't display the labels
Image

(it does have the right keys, so the form sets the right value)

### System configuration
**Avo version**: 3.15.3

**Rails version**: 7.2

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [X] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [X] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [X] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #3539

Fixes radio field labels to ensure proper association with options. Clicking a label now correctly selects the corresponding radio button, improving usability and accessibility. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: spec/features/avo/radio_field_spec.rb [hunk 1]
```diff
@@ -62,4 +62,21 @@
...
+      expect(page).not_to have_text("Small Option")
+      expect(page).not_to have_text("Medium Option")
+      expect(page).not_to have_text("Large Option")
+
+      open_panel_action(action_name: "Dummy action")
+
+      expect(page).to have_text("Small Option")
+      expect(page).to have_text("Medium Option")
+      expect(page).to have_text("Large Option")
+
```
Comment (Paul-Bob) [inline spec/features/avo/radio_field_spec.rb:79]:
```suggestion
```
