### PR TITLE
fix & refactor: select field

### LINKED ISSUE #1371: select field not working
From [here](https://github.com/avo-hq/avobookr/issues/1).

### Describe the bug

Cloning and running the example application in the repo - when setting a value via a select field, it does not get displayed later on even though all values are properly set in the database. This happens for both, the version 2.7 of avo, as well as for the latest (2.18).

### Steps to Reproduce
1. Clone the example "avobookr" repository. Install gems and setup DB.
2. Go to '/avo' and signup/login
3. Create a new booking
4. In the details page of the booking (http://localhost:3000/avo/resources/bookings/2), the column for "Booked for" is empty

### Expected behavior & Actual behavior

It should show the value as seen in the demo video (https://www.youtube.com/watch?v=BK47E7TMXn0&t=84s)

### System configuration
**Avo version**:
2.7 and 2.18
**Rails version**:

**Ruby version**:

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

image

### Additional context

- 
#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [ ] Medium urgency
 - [x] low urgency

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1371

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: spec/dummy/app/avo/resources/product_resource.rb [hunk 1]
```diff
@@ -11,13 +11,22 @@ class ProductResource < Avo::BaseResource
...
+      wrapper: {
+        classes: "bg-gray-50 !text-pink-600"
       }
     }
   }
   field :description, as: :trix
   field :image, as: :file, is_image: true
   field :price, as: :number
   field :category, as: :select, enum: ::Product.categories
+  field :vat_tax, as: :select, options: {
```
Comment (Paul-Bob) [inline spec/dummy/app/avo/resources/product_resource.rb:24]: - rm migration and field and make select options with temporary fields in city population.

- test filters with enum array and with enum hash

File: lib/avo/fields/select_field.rb [hunk 2]
```diff
@@ -19,45 +19,50 @@ def initialize(id, **args, &block)
...
+
+        computed_options = options.call model: model, resource: resource, view: view, field: self
+        return computed_options.invert.stringify_keys[value]
+      end
+
+      def value_from_enum
+        display_value ? options[value] : value
+      end
+
+      def value_from_options
```
Comment (Paul-Bob) [inline lib/avo/fields/select_field.rb:62]: with_indiferent_acces`

**Comment by adrianthedev** [comment]
Amazing work @Paul-Bob! Thank you for digging into this and fixing my past mistakes 🙃
