### PR TITLE
Fix `belongs_to` and ID field linking to child resources if configured

### LINKED ISSUE #2629: STI: field with link_to_record does not link to child resource
### Describe the bug
The hyperlinks added to some specific field using the option `link_to_record` do not behave consistently with the `link_to_child_resource` option set on the resource. 

### Steps to Reproduce
1. add `self.link_to_child_resource = true` on the parent resource, e.g. Person
2. visit the index page, observe that the eye button to go to the show page links to the sub-type (e.g. Spouse) as intended
3. define a field e.g. `field :name, as: :text, link_to_record: true`: observe that it does not link to the spouse resource but to the person resource

### Expected behavior & Actual behavior
A field with link_to_record: true should link to the child resource when link_to_child_resource has been set on the parent resource.

### System configuration
**Avo version**: 3.5.4

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [x] Low urgency (It can wait. I just wanted you to know about it.)

### LINKED ISSUE #2782: ID field within has_many field does not link to child resource
### Describe the bug
The ID field within a `has_many` field always links to the base class resource even when `link_to_child_resource` is true.

### Steps to Reproduce

Consider having the setup in the STI example here: https://docs.avohq.io/2.0/associations.html#link-to-child-resource-when-using-sti

1. In the `avo.rb` initializer, enable `id_links_to_resource`: `config.id_links_to_resource = true`
2. Go to the Show page of the resource that has the `peoples` field
3. Click on the linked ID column of one of the peoples row
4. You will be take to the resource Show page of the base class (PersonResource)

### Expected behavior & Actual behavior
When you click on the linked ID column, the expectation is that it will take you to the show page of the child resource (SpouseResource or SiblingResource).  Instead it takes you to the base class resource (PersonResoure).  If you use the View icon button, it will actually take you to the correct child record.

### System configuration
**Avo version**: 3.3.2

**Rails version**: 7.1 3

**Ruby version**: 3.2.2

**License type**:

 - [ ] Community
 - [x] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by stevegeek**
# Description

If a resource includes a `belongs_to` field which relates to a record which uses STI, then the current behaviour is that the link rendered on the `show` page for the resource to the associated record always links to the parent class resource. In other places this behaviour is controlled by `link_to_child_resource` but not here. 

Related, if `id_links_to_resource` is used and `link_to_child_resource` is set for an association, the link does not respect the `link_to_child_resource` setting.

This PR updates the `belongs_to` field to respect the `link_to_child_resource` option, which can either be set on the Resource, or set on the field.

It also changes the way BaseComponent determines if a field should `link_to_child_resource` by using the association reflection and checking the related association.

I believe this fixes #2629 and fixes #2782

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

I have checked this in an application using Avo but can't share screenshots from it.

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: app/components/avo/base_component.rb [hunk 1]
```diff
@@ -57,12 +57,14 @@ def parent_or_child_resource
...
   def link_to_child_resource_is_enabled?
-    return field_linked_to_child_resource? if @parent_resource
+    enabled = field_linked_to_child_resource? if @parent_resource
+    return enabled unless enabled.nil?
 
     @resource.link_to_child_resource
   end
 
   def field_linked_to_child_resource?
+    field = @parent_resource.get_field(@reflection.name) if @reflection
```
Comment (stevegeek) [inline app/components/avo/base_component.rb:67]: oh wait this is confusing, shadowing the method

**Comment by stevegeek** [comment]
@Paul-Bob @adrianthedev , if there is anything I can do to help you guys with reviewing this PR, do let me know

**Comment by Paul-Bob** [comment]
I'm reviewing it, thank you @stevegeek

**Comment by Paul-Bob** [comment]
> I believe this fixes #2629 and #2782

#2629 is already fixed, I verified it here https://main.avodemo.com/avo/resources/people

Is indeed fixing #2782, confirmed on the reproduction repo provided by @cyu

File: app/components/avo/base_component.rb [hunk 2]
```diff
@@ -57,12 +57,14 @@ def parent_or_child_resource
...
-    return field_linked_to_child_resource? if @parent_resource
+    enabled = field_linked_to_child_resource? if @parent_resource
+    return enabled unless enabled.nil?
 
     @resource.link_to_child_resource
   end
 
   def field_linked_to_child_resource?
-    field.present? && field.respond_to?(:link_to_child_resource) && field.link_to_child_resource
+    resolved_field = @reflection ? @parent_resource.get_field(@reflection.name) : field
```
Comment (Paul-Bob) [inline app/components/avo/base_component.rb:67]: I guess this will not find the field when using `for_attribute` option. For example:

```ruby
field :the_children, as: :has_many, for_attribute: :children, link_to_child_resource: true
```

This should cover that scenario, can you please verify that?

```suggestion
    resolved_field = @reflection ? @parent_resource.get_field(params[:for_attribute] || @reflection.name) : field
```

**Review by Paul-Bob — COMMENTED** [review]
I added a comment to cover the `for_attribute` scenario, otherwise, it's looking great @stevegeek! Thank you!

File: spec/features/avo/link_to_child_resource_spec.rb [hunk 3]
```diff
@@ -19,6 +27,36 @@
       end
     end
 
+    context "Resource show page links to associated resources" do
+      let(:paul) { create :sibling, name: "paul" }
```
Comment (Paul-Bob) [inline spec/features/avo/link_to_child_resource_spec.rb:31]: Great name! :D

**Comment by adrianthedev** [comment]
Thanks @stevegeek. 
FYI, we have a major Holiday today and we'll probably be back at it on Monday.
