### PR TITLE
fix: ActionText support for trix field

### LINKED ISSUE #2538: After uploading File in ActionText (Trix) it can not be found when rendering (missing attachable)
### Steps to Reproduce
1. Go to https://main.avodemo.com/avo/resources/posts/new
2. Insert Title and save
3. Edit Post
4. In BODY field attach non image File (for example README.md)
5. Save and "show content"
6. No uploaded file is shown

### Expected behavior & Actual behavior

Expected behaviour would be to show the uploaded file, actual behaviour is showing nothing.

I replicated the problem on a fresh minimal setup (https://github.com/tamaloa/AvoActionTextAttachmentTest ).
If using the rails built in create action (and trix editor) a upload is rendered in rails view as expected (via` _blob.html.erb` partial).
If adding a file to a actiontext via AVO gem the attachment does not seem to be found.

Stacktrace from showing a resource created with avo (with file upload)

```
Processing by NotesController#show as HTML
  Parameters: {"id"=>"2"}
  Note Load (0.1ms)  SELECT "notes".* FROM "notes" WHERE "notes"."id" = ? LIMIT ?  [["id", 2], ["LIMIT", 1]]
  ↳ app/controllers/notes_controller.rb:63:in `set_note'
  Rendering layout layouts/application.html.erb
  Rendering notes/show.html.erb within layouts/application
  ActionText::RichText Load (0.1ms)  SELECT "action_text_rich_texts".* FROM "action_text_rich_texts" WHERE "action_text_rich_texts"."record_id" = ? AND "action_text_rich_texts"."record_type" = ? AND "action_text_rich_texts"."name" = ? LIMIT ?  [["record_id", 2], ["record_type", "Note"], ["name", "content"], ["LIMIT", 1]]
  ↳ app/views/notes/_note.html.erb:4
  Rendered .rvm/gems/ruby-3.2.2/gems/actiontext-7.1.3.2/app/views/action_text/attachables/_missing_attachable.html.erb (Duration: 0.2ms | Allocations: 116)
  Rendered .rvm/gems/ruby-3.2.2/gems/actiontext-7.1.3.2/app/views/action_text/contents/_content.html.erb within layouts/action_text/contents/_content (Duration: 5.9ms | Allocations: 10446)
  Rendered notes/_note.html.erb (Duration: 29.8ms | Allocations: 30333)
  Rendered notes/show.html.erb within layouts/application (Duration: 34.2ms | Allocations: 33322)
  Rendered layout layouts/application.html.erb (Duration: 75.0ms | Allocations: 83570)
Completed 200 OK in 116ms (Views: 77.1ms | ActiveRecord: 1.7ms | Allocations: 106168)
```

### Models and resource files

 https://github.com/tamaloa/AvoActionTextAttachmentTest

### System configuration
ruby 3.2.2, rails 7.1.3.2, avo (3.4.2)

**License type**:

 - [x] Community
 - [ ] Pro
 - [ ] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/avo-hq/avo/assets/118779/95d90bad-86c1-4031-868a-66edb88db8a5

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

Workaround is to let users upload Files via a standard rails edit view which is far from ideal :(

### LINKED ISSUE #2638: Embedding images in Trix editor does not work
### Describe the bug
Embedding images in Trix editor either leads to error or results in images which do not persist (see below).

### Steps to Reproduce
1. Create a resource with `field :body, as: :trix`
2. Create a new record
3. Go back to the edit page
4. Click on the paperclip icon in the Trix toolbar for this field
5. Select some image file

### Expected behavior & Actual behavior
Expected: the image gets inserted. After saving, it renders correctly.

Actual: error `You haven't set an `attachment_key` to this Trix field.` But the [documentation](https://docs.avohq.io/3.0/fields/trix.html#attachment_key) does not specify which value should be put for `attachment_key`. I tried `embeds` and `trix_attachments`, neither of those allow to embed images which persist after saving. Besides, Avo should be able to figure out by itself what is required: we have been able to embed images without specifying any "attachment key" when using Administrate.

### Models and resource files

```rb
class Article < ApplicationRecord
  has_rich_text :body
end
```

```rb
class Avo::Resources::Article < Avo::BaseResource
  def fields
    field :body, as: :trix
  end
end
```

### System configuration
**Avo version**: 3.5.5

**Rails version**: 7.0.8.1

**Ruby version**: 3.3.0

**License type**:
 - [x] Community
 - [ ] Pro
 - [ ] Advanced

#### Impact
 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

The only workaround known to us currently is to stop Avo development and continue to rely on Administrate as far as these resources are concerned.

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #2638 
Fixes #2538

This PR removes the need of `attachment_key` on the `trix` field when using `has_rich_text`.
Also refactored the JS code to use values instead dataset.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: lib/avo/fields/trix_field.rb [hunk 1]
```diff
@@ -21,6 +21,11 @@ def initialize(id, **args, &block)
         @hide_attachment_url = args[:hide_attachment_url] || false
       end
 
+      # Identify if field is bonded to a rich text model attribute
+      def is_active_text?
```
Comment (sedubois) [inline lib/avo/fields/trix_field.rb:25]:
```diff
-      def is_active_text?
+      def is_action_text?
```

File: app/components/avo/fields/trix_field/edit_component.rb [hunk 2]
```diff
@@ -5,25 +5,30 @@ class Avo::Fields::TrixField::EditComponent < Avo::Fields::EditComponent
 
   def initialize(**args)
     @resource = args[:resource]
-    @resource_id = args[:resource_id]
-    @resource_name = args[:resource_name]
+    @resource_id = args[:resource_id] || @resource&.record&.id
```
Comment (Paul-Bob) [inline app/components/avo/fields/trix_field/edit_component.rb:8]:
```suggestion
    @resource_id = args[:resource_id] || @resource&.record&.to_param
```

**Review by adrianthedev — APPROVED** [review]
Looks good!
Manual tested and it works
