### PR TITLE
fix: resource getting wrong model

### LINKED ISSUE #1444: Missing resources inside action visible block
### missing resources inside action visible block

```ruby
   class SetToPrimaryAction < ::ApplicationBaseAction
    self.name = "SetToPrimary"

    self.visible = lambda do
      begin
        return false unless view == :show || view == :index

        # we expect the parent_resource and resource to be different 
      end
    end
```
the resource we receive in the visible block is always the parent resource. Regardless if the action is involved in
a regular show view or in an index view for the  has_many association. 
We are expecting to get the resource of the has_many association . 
can u please confirm the problem/bug  ?

### Steps to Reproduce
1. checkout the demo code https://github.com/elassadi/avo-demo
2. create a post and a comment 
3. hit http://127.0.0.1:3000/avo/resources/posts/1
4. check the debug log 

### Expected behavior & Actual behavior

parent_resource and resource should be targeting the association resource  and the parent resource respectively
### System configuration
**Avo version**: latest

**Rails version**:

**Ruby version**:

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

#### Impact

 - [] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1444

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: lib/avo/base_resource.rb [hunk 1]
```diff
@@ -151,7 +151,7 @@ def hydrate(model: nil, view: nil, user: nil, params: nil)
       @user = user if user.present?
       @params = params if params.present?
 
-      if model.present?
+      if model.present? && model.class == model_class
```
Comment (adrianthedev) [inline lib/avo/base_resource.rb:154]: I'm not sure this is the proper place to fix this. I mean, `BaseResource.model_class` falls back to computing the model class based on it's own name.
It seems a bit arbitrary.

How about finding the place where we wrongly hydrate that resource and applying the fix there?

Comment (Paul-Bob) [reply lib/avo/base_resource.rb]: Hmm, the issue starts here:

image

I'm not sure how we can verify it without model_class... Yes, mostly it's computed but sometimes it's not, and i think this covers both situations. It's there any situation where we want a resource to have a model different from his model_class, ancestors or dependents?

Comment (adrianthedev) [reply lib/avo/base_resource.rb]: What I mean is, fix the issue where we run `resource.hydrate(model: WRONG_MODEL)` instead of checking inside the resource. Because it's clear to me that somewhere we're making that mistake.

Comment (Paul-Bob) [reply lib/avo/base_resource.rb]: Got it, i agree, issue found: 

image

File: app/controllers/avo/application_controller.rb [hunk 2]
```diff
@@ -176,7 +176,8 @@ def hydrate_resource
     end
 
     def hydrate_related_resource
-      @related_resource.hydrate(view: action_name.to_sym, user: _current_user, model: @model)
+      model = @related_resource.model_class == @model.class ? @model : nil
```
Comment (adrianthedev) [inline app/controllers/avo/application_controller.rb]: I think this check will fail if the referenced association is of the same model like `Comment` -> `has_many` -> `Comments`. The wrong model will be associated.

We should check **why** is a model hydrated there, and which one.

**Review by adrianthedev — COMMENTED** [review]
I pushed some changes.

I think the error was that we were hydrating the `parent_resource` with the `model` instead of the `parent_model`. We also missed to hydrate the `resource` with `model`, which I added here.

WDYT about this approach?

**Comment by adrianthedev** [comment]
The gist is that you won't have a `resource.model` (a user in our example) available in the action `visible` block, in an index view of users because there are many, not one. Instead, in a `has_one` (Team has one admin), you'll have it.

**Comment by adrianthedev** [comment]
I released `2.21.1.pre.issue1444` to test out.

**Comment by Paul-Bob** [comment]
> I pushed some changes.
> 
> I think the error was that we were hydrating the `parent_resource` with the `model` instead of the `parent_model`. We also missed to hydrate the `resource` with `model`, which I added here.
> 
> WDYT about this approach?

Much better, straight to the point!
