### PR TITLE
fix: actions download

### LINKED ISSUE #2184: Fix `ActionController::UnknownFormat` on download actions
### Describe the bug
When early returning an error or something on an action that have `  self.may_download_file = true` an `ActionController::UnknownFormat` error is raised.

Action code:
```ruby
class Avo::Actions::ExportCsv < Avo::BaseAction
  self.name = "Export csv"
  self.no_confirmation = false
  self.may_download_file = true

  def handle(**args)
    return error "Error"
  end
end

```

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #2184 

- `may_download_file` become deprecated and is no longer being used, can safely be removed from all actions.
- Fixes early error messages return on download actions
- Fixes keep modal open feature on download actions
- Refactors the way that actions download works
  - Use turbo stream to a custom stream action that triggers the download using [FileSaver.js lib](https://www.npmjs.com/package/file-saver)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
  - https://github.com/avo-hq/avodocs/pull/154
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: app/javascript/js/controllers/modal_controller.js [hunk 1]
```diff
@@ -1,20 +0,0 @@
-import { Controller } from '@hotwired/stimulus'
-
-export default class extends Controller {
-  static targets = ['modal']
-
-  close() {
-    this.modalTarget.remove()
-
-    document.dispatchEvent(new Event('actions-modal:close'))
-  }
```
Comment (Paul-Bob) [inline app/javascript/js/controllers/modal_controller.js:10]: this still being used

Comment (Paul-Bob) [reply app/javascript/js/controllers/modal_controller.js:10]: add tests for it...

File: app/views/avo/actions/download.turbo_stream.erb [hunk 2]
```diff
@@ -0,0 +1,16 @@
+<%# Append a div that triggers the download_controller.js %>
+<%= turbo_stream.append "actions_show" do %>
+  <%= content_tag :div,
+    data: {
+      controller: "download",
+      content: @response[:path],
+      filename: @response[:filename],
+    } do %>
+  <% end %>s
```
Comment (Paul-Bob) [inline app/views/avo/actions/download.turbo_stream.erb:9]:
```suggestion
  <% end %>
```

**Review by adrianthedev — APPROVED** [review]
If we have tests supporting this use case, then it's good to merge.

Thank you!

**Comment by Paul-Bob** [comment]
> If we have tests supporting this use case, then it's good to merge.
> 
> Thank you!

We have several tests around actions, download, keeping modal open, alerts, etc... Are all being already tested.
