### PR TITLE
fix: `belongs_to` index field name

### LINKED ISSUE #2099: `belongs_to` fields not applying `name` option on index view
### Describe the bug

`belongs_to` fields are not applying `name` option on index view.

`field :commentable, as: :belongs_to, polymorphic_as: :commentable, types: [::Post, ::Project], name: "Test"`

### Index
image

### Show
image

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

`belongs_to` name on index was hard-coded.

Fixes #2099 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: lib/avo/fields/belongs_to_field.rb [hunk 1]
```diff
@@ -259,8 +259,8 @@ def get_model
         nil
       end
 
-      def name
-        return polymorphic_as.to_s.humanize if polymorphic_as.present? && view.index?
```
Comment (adrianthedev) [inline lib/avo/fields/belongs_to_field.rb:263]: Removing `&& view.index?` is ok? I mean it does seem to have it's place...

Comment (Paul-Bob) [reply lib/avo/fields/belongs_to_field.rb:263]: I think so, why we would apply the polymorphic_as default name only on index? That means that on other views would fallback to 

```ruby
def default_name
    @id.to_s.humanize(keep_id_suffix: true)
  end
```
