### PR TITLE
fix: allow all chars on text filters

### LINKED ISSUE #2061: The TextFilter function cannot search for some characters
### Describe the bug
- The TextFilter function cannot search for some characters.
  - Search may not be possible in languages other than English. The impact is likely to be especially large in Asia in general.

### Steps to Reproduce
1. Access at https://avodemo.com/avo/resources/users
2. Press the Filter button
3. Enter the word `(` or `音楽` in the User names filter input form (音楽 means music in Japanese).
4. Click the Filter by user names button
5. javascript error and cannot search
```
stimulus.js:2017 Error invoking action "keypress->text-filter#tryToSubmit"
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at n.b64DecodeUnicode (filter_controller.js:38:12)
    at n.changeFilter (filter_controller.js:50:33)
    at n.tryToSubmit (text_filter_controller.js:12:19)
    at tse.invokeWithEvent (stimulus.js:362:25)
    at tse.handleEvent (stimulus.js:329:18)
    at Xae.handleEvent (stimulus.js:31:25)

{identifier: 'text-filter', controller: n, element: div, index: 0, event: KeyboardEvent}controller: n {context: fse}element: divevent: KeyboardEvent {isTrusted: true, immediatePropagationStopped: false, params: {…}, key: 'Enter', stopImmediatePropagation: ƒ, …}identifier: "text-filter"index: 0[[Prototype]]: Object
handleError @ stimulus.js:2017
handleError @ stimulus.js:1423
invokeWithEvent @ stimulus.js:368
handleEvent @ stimulus.js:329
handleEvent @ stimulus.js:31
```

### Expected behavior & Actual behavior
To be able to search by text entered in text-filte.

### System configuration
**Avo version**:
3.0.6

**Rails version**:
7.1.2

**Ruby version**:
3.2.2

**License type**:
 - [ ] Community
 - [ ] Pro
 - [x] Advanced

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings
https://github.com/avo-hq/avo/assets/14293538/068e30b9-cb6a-49bd-9689-4df28f0211e4

https://github.com/avo-hq/avo/assets/14293538/92dc9def-88d4-4d2f-97be-af12e0d42189

#### Impact
We plan to temporarily disable the text filter for all resources to work around this issue.

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency
 - [x] High urgency (I can't continue development without it.)
 - [ ] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #2061 

1. Encode and decode filters on JS controller following [mdn official documentation about "the unicode problem"](https://developer.mozilla.org/en-US/docs/Glossary/Base64#the_unicode_problem)
2. Un-silence decoding errors, we had some suppressed errors, that makes some bugs hard to debug and understand. 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: app/controllers/avo/base_controller.rb [hunk 1]
```diff
@@ -51,6 +51,7 @@ def index
       end
 
       # Apply filters to the current query
+
```
Comment (Paul-Bob) [inline app/controllers/avo/base_controller.rb:54]:
```suggestion
```

**Comment by yuki-yogi** [comment]
@Paul-Bob 
Thanks for creating the issue.
I was about to report this issue as well.

I am attaching a video just in case.
This issue also occurs at avo 3.1.0.

https://github.com/avo-hq/avo/assets/14293538/aec5b64c-1c1d-45f1-858d-dc29f07a47fb

```
stimulus.js:2017 Error invoking action "keypress->text-filter#tryToSubmit"

URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at n.b64DecodeUnicode (filter_controller.js:38:12)
    at n.changeFilter (filter_controller.js:50:33)
    at n.tryToSubmit (text_filter_controller.js:12:19)
    at tse.invokeWithEvent (stimulus.js:362:25)
    at tse.handleEvent (stimulus.js:329:18)
    at Xae.handleEvent (stimulus.js:31:25)

{identifier: 'text-filter', controller: n, element: div, index: 0, event: KeyboardEvent}
controller
: 
n {context: fse}
element
: 
div
event
: 
KeyboardEvent {isTrusted: true, immediatePropagationStopped: false, params: {…}, key: 'Enter', stopImmediatePropagation: ƒ, …}
identifier
: 
"text-filter"
index
: 
0
[[Prototype]]
: 
Object
```

**Comment by Paul-Bob** [comment]
@yuki-yogi this is actually an PR to fix [this issue](https://github.com/avo-hq/avo/issues/2061) that was created by you! =))

**Comment by yuki-yogi** [comment]
@Paul-Bob 
Ah, I understand!
Thanks for the PR response to the fix!

Looking forward to the next release.

**Review by adrianthedev — APPROVED** [review]

**Comment by Paul-Bob** [comment]
@yuki-yogi this should be fixed on the last patch release ;)

**Comment by yuki-yogi** [comment]
@Paul-Bob 
Understood. Thank you for your report!
The filter function is often used, so we look forward to seeing it fixed!

**Comment by Paul-Bob** [comment]
@yuki-yogi let us know if it works as expected on [`3.1.5`](https://rubygems.org/gems/avo/versions/3.1.5)

**Comment by yuki-yogi** [comment]
@Paul-Bob 
We immediately deployed avo 3.1.5 to the production environment and confirmed that the problem was resolved!

Thank you so much for your help.
Thanks for solving this problem, I will add self.keep_filters_panel_open = true to each resourece so that users can use the filter function more.
