### PR TITLE
Fix: Always display persisted image in the edit view

### LINKED ISSUE #3008: Handle case when record is invalid and new image is attached
### Describe the bug

Avo breaks when the user adds a new image, makes an error in other form field, and tries to save/update the record.

### Steps to Reproduce

I was able to reproduce the issue using the [main.avodemo.com](https://main.avodemo.com) app:

1. [Open Posts](https://main.avodemo.com/avo/resources/posts/)
2. Edit existing post:
- remove `name` (which is required)
- attach new `cover photo`
- click on save

### Expected behavior & Actual behavior

_Expected behavior:_
The form is displayed again with errors.

_Actual behavior:_
App crashes with `ArgumentError: "Cannot get a signed_id for a new record"`. 
The problem is with `app/components/avo/fields/common/files/view_type/grid_item_component.html.erb`, line: 5. `helpers.main_app.url_for(file)` does not work. 

### System configuration

Avo version: 3.10.6

Rails version: 7.2 beta

**License type**:

 - [ ] Community
 - [ ] Pro
 - [x] Advanced

#### Impact

 - [ ] High impact (It makes my app un-usable.)
 - [x] Medium impact (I'm annoyed, but I'll live.)
 - [ ] Low impact (It's really a tiny thing that I could live with.)

#### Urgency

 - [ ] High urgency (I can't continue development without it.)
 - [x] Medium urgency (I found a workaround, but I'd love to have it fixed.)
 - [ ] Low urgency (It can wait. I just wanted you to know about it.)

### PR DESCRIPTION
**Pull request by binarygit**
# Description

Fixes #3008

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Navigated to /resources/post/<id>/edit
2. Deleted text from name field
3. Clicked on Browse and attached a new image
4. Hit save
5. Ensured that error message is rendered on screen and app doesn't crash.

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

**Review by Paul-Bob — CHANGES_REQUESTED** [review]
Noticed that a dash (`–`) remains while reproducing the bug, let's try to remove the dash in that scenario.

# Expected (trying other flux just to show the UI expectations):

[expected.webm](https://github.com/user-attachments/assets/4cb300f5-cfcd-423f-8a57-3fec1e45c46b)


# Actual: 

[actual.webm](https://github.com/user-attachments/assets/787ecd79-0a9e-4760-a2d4-2a042f7ebedc)

**Comment by adrianthedev** [comment]
Yes, we need to take into account how it behaves when updating.

**Comment by binarygit** [comment]
https://github.com/user-attachments/assets/0929f848-d897-4453-944d-87cae067248c

@Paul-Bob Pushed a commit which fixes this.

**Comment by Paul-Bob** [comment]
@binarygit still the dash appear on show view when there is no file attached?

**Comment by binarygit** [comment]
@Paul-Bob yes, sir :saluting_face: . It does

image

**Comment by Paul-Bob** [comment]
I noticed a strange behavior, here is a video that explains it:

[strange_behaviour.webm](https://github.com/user-attachments/assets/79482ec1-40aa-4e33-9c2d-fb4cc48f382f)

File: lib/avo/fields/base_field.rb [hunk 1]
```diff
@@ -162,6 +162,12 @@ def value(property = nil)
           final_value = computed_default_value
         end
 
+        # On edit view always show the persisted image. Related: issue#3008
+        if final_value.instance_of?(ActiveStorage::Attached::One) && final_value.image? && view == "edit"
+          persisted_record = record.class.find_by(id: record.id)
+          final_value = persisted_record.send(property)
+        end
```
Comment (adrianthedev) [inline lib/avo/fields/base_field.rb:169]: THis should go to the file field or somewhere else. THis doesn't pertaing to the base field

**Review by adrianthedev — CHANGES_REQUESTED** [review]
!

File: app/components/avo/fields/common/files/view_type/grid_item_component.html.erb [hunk 2]
```diff
@@ -1,5 +1,9 @@
 <div id="<%= dom_id file %>" class="relative min-h-full max-w-full flex-1 flex flex-col justify-between space-y-2">
-  <% if file.present? %>
+  <%# When editing a resource, if you attach a file and also edit another field which causes a validation error.
+      In such a situation, file is an object that hasn't been saved to the database (i.e id == nil) because
+      the resource update failed and so the attachment wasn't persisted.
+      In such situations url_for(file) will complain that it can't find the url for an non-existent file. %>
+  <% if file.persisted? %>
```
Comment (Paul-Bob) [inline app/components/avo/fields/common/files/view_type/grid_item_component.html.erb:6]: Is this change still necessary if we always display the persisted image?

Comment (binarygit) [reply app/components/avo/fields/common/files/view_type/grid_item_component.html.erb:6]: I think it's better than `file.present?` because it's more clear that the code inside the block needs to execute only if we have a persisted file.

File: lib/avo/fields/base_field.rb [hunk 3]
```diff
@@ -162,6 +162,12 @@ def value(property = nil)
...
+
```
Comment (Paul-Bob) [inline lib/avo/fields/base_field.rb:170]: Let's remove this since it's already on `file_field.rb`

File: lib/avo/fields/file_field.rb [hunk 4]
```diff
@@ -24,6 +24,17 @@ def initialize(id, **args, &block)
       def path
         rails_blob_url value
       end
+
+      def value
+        final_value = super
+        # On edit view always show the persisted image. Related: issue#3008
+        if final_value.instance_of?(ActiveStorage::Attached::One) && final_value.image? && view == "edit"
```
Comment (Paul-Bob) [inline lib/avo/fields/file_field.rb:31]: > `final_value.image?`

Should we apply this only to images? I think we should remove that guard and apply this behavior to all file types, WDYT?

**Review by Paul-Bob — CHANGES_REQUESTED** [review]
Let's remove the duplicated code and verify if we should keep same approach for all file types

File: lib/avo/fields/file_field.rb (hunk 4 above)
Comment (binarygit) [reply lib/avo/fields/file_field.rb:31]: Agreed. I'll look into it

File: app/components/avo/fields/common/files/view_type/grid_item_component.html.erb (hunk 2 above)
Comment (Paul-Bob) [reply app/components/avo/fields/common/files/view_type/grid_item_component.html.erb:6]: Not saying `file.present?` is better, just wondering if this check is necessary or redundant since we already guarantee to show only persisted files

Comment (binarygit) [reply app/components/avo/fields/common/files/view_type/grid_item_component.html.erb]: True. I removed the conditional. There's a failing test in CI but it passes locally for me.

File: app/components/avo/fields/common/files/view_type/grid_item_component.html.erb [hunk 5]
```diff
@@ -1,27 +1,23 @@
 <div id="<%= dom_id file %>" class="relative min-h-full max-w-full flex-1 flex flex-col justify-between space-y-2">
-  <% if file.present? %>
```
Comment (adrianthedev) [inline app/components/avo/fields/common/files/view_type/grid_item_component.html.erb:2]: The field wrapper will intercept and not render this component. That's why we don't need the `file.present?` line.

**Review by adrianthedev — APPROVED** [review]
Looks good. haven't manually tested the scenario.

File: lib/avo/fields/file_field.rb [hunk 6]
```diff
@@ -24,6 +24,16 @@ def initialize(id, **args, &block)
       def path
         rails_blob_url value
       end
+
+      def value
+        final_value = super
+        # On edit view always show the persisted image. Related: issue#3008
+        if final_value.instance_of?(ActiveStorage::Attached::One) && view == "edit"
+          persisted_record = record.class.find_by(id: record.id)
+          final_value = persisted_record.send(@for_attribute || id)
```
Comment (Paul-Bob) [inline lib/avo/fields/file_field.rb:33]: @binarygit do you think it's possible to use some active record helper to reload `@for_attribute || id` from the `@record` while keeping other attributes dirty? This way we can avoid the manual `find_by` query...

Comment (binarygit) [reply lib/avo/fields/file_field.rb:33]: I’ll look into it paul

Comment (binarygit) [reply lib/avo/fields/file_field.rb:33]: @Paul-Bob I looked but there's no straight forward way to do this. I tried to dup the record and clear specific changes but the changes propagated to the original record too which we shouldn't let happen.
