### PR TITLE
fix: remove duplicate create method

### LINKED ISSUE #1944: Weird behavior when creating a model from a has_many field
### Context

I have a model which `belongs_to` another model
```ruby
create_table :notes do |t|
  t.text :note, null: false
  t.belongs_to :provider, null: false, foreign_key: true
end
```
```ruby
class Note < ApplicationRecord
  belongs_to :provider

  validates :note, presence: true
end
```

then on the parent resource i have a `has_many` field
```ruby
field(:notes, as: :has_many)
```

When i try to create a new note the UI says the creation failed but the note is created successfully

I am not sure if i missed something and this is expected but i took a quick look at the source code and believe that the issue is [Here](https://github.com/avo-hq/avo/blob/8f780eca21e0e80595925aece6f76f703ec78a22/app/controllers/avo/base_controller.rb#L129C9-L129C9), the controller tries to save the model before setting `provider_id` which fails (This would be the error reported on the UI) but then [later on](https://github.com/avo-hq/avo/blob/8f780eca21e0e80595925aece6f76f703ec78a22/app/controllers/avo/base_controller.rb#L144) the model is saved again after setting `provider_id` and succeds.

as a work around i am overriding the `save_model_action` method on the `NotesController`
```ruby
class Avo::NotesController < Avo::ResourcesController
  def save_model_action
    true
  end
end
```

with that creating notes works as expected

### System configuration
**Avo version**: 2.36.2

**Rails version**: 7.0.7.2

**Ruby version**: 3.2.0

**License type**

 - [x] Community
 - [x] Pro

**Are you using Avo monkey patches, overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

https://github.com/avo-hq/avo/assets/6798292/4e760788-373e-41cb-ae6c-c3dd0c89e4d0

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1944

Save record only once on creation after applying the associations logic.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: app/controllers/avo/base_controller.rb [hunk 1]
```diff
@@ -139,7 +135,6 @@ def create
           related_record = related_resource.find_record params[:via_record_id], params: params
 
           @record.send("#{@reflection.foreign_key}=", related_record.id)
```
Comment (adrianthedev) [inline app/controllers/avo/base_controller.rb:137]: Hmmm. Wouldn't this break if this is a new record and it's not persisted to the DB?

```ruby
user = User.new
user.post = Post.new # wouldn't this break if there were a FK constraint or validation rule?
user.save
```

Comment (Paul-Bob) [reply app/controllers/avo/base_controller.rb:137]: Actually this is being done:

```ruby
user = User.new
user.post_id = 4 # random id
user.save
```

`related_record` is already persistent

Comment (adrianthedev) [reply app/controllers/avo/base_controller.rb:137]: Got it! Then it's good to merge!

**Review by adrianthedev — APPROVED** [review]
