### PR TITLE
fix: secret key base warning

### LINKED ISSUE #2090: Fix `Rails.application.secrets.secret_key_base`
`Rails.application.secrets.secret_key_base` will be removed in rails `7.2`. We should assure that our `lib/avo/services/encryption_service.rb` do not call `Rails.application.secrets.secret_key_base` when rails version `>= 7.2`.

Also make sure that all avo packages use `ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base` to avoid warning logs.
```[tasklist]
### Tasks
- [x] Add `>= 7.2` condition before calling `Rails.application.secrets.secret_key_base`
- [x] Ensure `ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base` usage on all avo packages spec.
```

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #2090

- Only fetch secret key from `Rails.application.secrets.secret_key_base` if rails version is less than `7.2.0`
- Raise custom error when not on production
- Keep same behavior on production

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: spec/dummy/config/boot.rb [hunk 1]
```diff
@@ -3,6 +3,8 @@
 
 ENV["AVO_IN_DEVELOPMENT"] = "1"
 
+ENV["SECRET_KEY_BASE"] = "130b8d0a74b5b73bfb2d0505c3de8250"
```
Comment (adrianthedev) [inline spec/dummy/config/boot.rb:6]: Please remind me, why do we need the `ENV["SECRET_KEY_BASE"]`?

**Review by adrianthedev — APPROVED** [review]
Nice! GG!

File: spec/dummy/config/boot.rb (hunk 1 above)
Comment (Paul-Bob) [reply spec/dummy/config/boot.rb:6]: For features that uses the encryption service to work, for example select all that encrypts the `@query`

Comment (adrianthedev) [reply spec/dummy/config/boot.rb:6]: Oh, yeah. Makes sense. I was thinking about something else.
GOod to merge!

Comment (Paul-Bob) [reply spec/dummy/config/boot.rb:6]: Without this variable that features would not work properly on tests or dev. Another solution would be to configure it on development and test credential files.

Anyway `130b8d0a74b5b73bfb2d0505c3de8250` is just a random string, it can be anything. What is important is to use on decryption the same string used on encryption
