### PR TITLE
fix: action visibility on show controls

### LINKED ISSUE #1769: The action's `visible` block is not respected in the `action` show control
### Describe the bug

If an action has `self.visible = -> {false}`, the action is still displayed on the page if the `show_controls` uses it `action TheAction`

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1769

Action visibility block runs even on show controls actions now

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: lib/avo/resources/controls/action.rb [hunk 1]
```diff
@@ -4,17 +4,17 @@ module Controls
...
           @klass = klass
           @resource = resource
-          @model = model
+          @record = record
           @view = view
         end
 
         def action
-          @instance ||= @klass.new(model: @model, resource: @resource, view: @view)
+          @instance ||= @klass.new(model: @record, resource: @resource, view: @view)
```
Comment (Paul-Bob) [inline lib/avo/resources/controls/action.rb:17]: For some reason this class is initialized by `Avo::Resources::Controls::Action.new(klass, record: record, resource: resource, view: view, **args)` but the `initialize` method was not expecting the same argument name, using `model` instead `record`. (In avo3 this is already uniformed)

**Comment by adrianthedev** [comment]
Can we add some tests please?

**Review by adrianthedev — APPROVED** [review]
