### PR TITLE
fix: sidebar field visibility block

### LINKED ISSUE #1353: Visibility lambda/proc provided for a field in a sidebar is ignored
### Describe the bug

Inside a sidebar declaration of a resource, field visibility lambda will not be called

### Steps to Reproduce
1. Checkout demo repo at https://github.com/elassadi/avo-demo

```ruby 
class MammalResource < Avo::BaseResource
  self.title = :name
  self.model_class= "Mammal"
  self.includes = []
  # self.search_query = -> do
  #   scope.ransack(id_eq: params[:q], m: "or").result(distinct: false)
  # end

  field :id, as: :id
  field :name, as: :text
  field :farm, as: :belongs_to


  sidebar do
    field  :updated_at, as: :date, only_on: :show, visible: -> (resource:) {
        false
    }
  end

  # add fields here
end
```

### Expected behavior & Actual behavior

Field updated_at should not be visible in the sidebar 

### System configuration
**Avo version**:latest

**Rails version**:7.0.1

**Ruby version**:3.0.1

**License type**:

 - [x] Community
 - [ ] Pro

**Are you using Avo monkey patches or overriding views or view components?**

 - [ ] Yes. If so, please post code samples.
 - [x] No

### Screenshots or screen recordings

image

#### Impact

 - [ ] High impact
 - [x] Medium impact
 - [ ] Low impact

#### Urgency

 - [ ] High urgency
 - [x] Medium urgency
 - [ ] low urgency

### PR DESCRIPTION
**Pull request by Paul-Bob**
# Description

Fixes #1353

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

### CODE REVIEW

File: lib/avo/sidebar.rb [hunk 1]
```diff
@@ -45,16 +45,12 @@ def visible_items
     items.map do |item|
       # Remove the fields that shouldn't be visible in this view
       # eg: has_many fields on edit
-      if not_visible_field(item)
-        nil
-      else
-        item
-      end
+      visible_field(item) ? item : nil
```
Comment (adrianthedev) [inline lib/avo/sidebar.rb:48]: GG for the refactor! Not sure what I was thinking 😛
